"""Storage protocol for the ziva runtime.

The runtime talks to persistent state exclusively through this surface, so a
library user can swap the filesystem-backed :class:`FileStorage` for an
in-process :class:`InMemoryStorage` (or any custom implementation) by passing
``storage=`` to ``Runtime.from_config`` / ``ziva.Agent``.

Method signatures mirror :class:`ziva.storage.file_storage.FileStorage` and are
called positionally as ``storage.method(project_id, session_id, ...)`` — the
same call works whether ``storage`` is the ``FileStorage`` class (whose methods
are classmethods) or an ``InMemoryStorage`` instance.
"""

from __future__ import annotations

from typing import Any, Iterator, List, Optional, Protocol


class Storage(Protocol):
    """Session / message / project / automation persistence contract."""

    # ---- sessions ----
    def create_session(self, project_id: str, session_data: dict) -> None: ...
    def update_session(self, project_id: str, session_id: str, session_data: dict) -> None: ...
    def get_session(self, project_id: str, session_id: str) -> Optional[dict]: ...
    def list_sessions(self, project_id: str) -> List[dict]: ...
    def delete_session(self, project_id: str, session_id: str) -> None: ...

    # ---- messages (JSONL-style append log on FileStorage) ----
    def append_message(self, project_id: str, session_id: str, message_data: dict) -> None: ...
    def get_messages(self, project_id: str, session_id: str, locked: bool = False) -> Iterator[dict]: ...
    def update_message(self, project_id: str, session_id: str, message_id: str, message_data: dict) -> None: ...
    def replace_messages(self, project_id: str, session_id: str, messages: List[dict]) -> None: ...

    # ---- project ----
    def get_project(self, project_id: str) -> Optional[dict]: ...
    def save_project(self, project_id: str, project_data: dict) -> None: ...

    # ---- automations ----
    def list_automations(self, project_id: str) -> List[dict]: ...
    def replace_automations(self, project_id: str, automations: List[dict]) -> None: ...
    def upsert_automation(self, project_id: str, automation: dict) -> None: ...
    def delete_automation(self, project_id: str, automation_id: str) -> bool: ...

    # ---- layout (used by the desktop transport for attachments) ----
    def project_dir(self, project_id: str) -> Any: ...


__all__ = ["Storage"]
